apiVersion: apps/v1
kind: Deployment
metadata:
  name: notary-app-deployment
  namespace: notary-prod
spec:
  replicas: 2
  selector:
    matchLabels:
      app: notary-app
  template:
    metadata:
      labels:
        app: notary-app
    spec:
      containers:
      - name: app-container
        image: gcr.io/notary-management-web-platform/notary-app:latest
        ports:
        - containerPort: 8080
