apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: notary-app-ingress
  namespace: notary-prod
  annotations:
    kubernetes.io/ingress.global-static-ip-name: "8.233.11.245" # Link a reserved static IP
    networking.gke.io/managed-certificates: "notary-ssl-cert"       # Setup managed Google SSL
spec:
  rules:
  - host: app.notarialsolutions.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: notary-app-service
            port:
              number: 80
